DROP TABLE Assets_History IF EXISTS;
DROP TABLE Comments IF EXISTS;
DROP TABLE Audti_Track IF EXISTS;
DROP TABLE Assets_User IF EXISTS;
DROP TABLE User_Info IF EXISTS;
DROP TABLE Asset_Type IF EXISTS;
DROP TABLE Assets IF EXISTS;

DROP SEQUENCE USER_SEQ IF EXISTS; 
DROP SEQUENCE ASSET_SEQ IF EXISTS; 
DROP SEQUENCE UNI_SEQ IF EXISTS; 
DROP SEQUENCE HISTORY_SEQ IF EXISTS;


